[adapter]
# The configuration file for mgw
[adapter.server]
host = "0.0.0.0"
port = "9843"
publicKeyPath = "/home/wso2/security/localhost.pem"
privateKeyPath = "/home/wso2/security/localhost.key"
[[adapter.server.users]]
username = "admin"
password = "admin"

[envoy]
listenerHost = "0.0.0.0"
listenerPort = 9095
clusterTimeoutInSeconds = 20
listenerTLSEnabled = true
listenerCertPath = "/home/wso2/security/mg.pem"
listenerKeyPath = "/home/wso2/security/mg.key"

[envoy.upstream]
[envoy.upstream.tls]
minimumProtocolVersion = "TLS1_1"
maximumProtocolVersion = "TLS1_2"
ciphers = "ECDHE-ECDSA-AES128-GCM-SHA256, ECDHE-RSA-AES128-GCM-SHA256, ECDHE-ECDSA-AES128-SHA, ECDHE-RSA-AES128-SHA, AES128-GCM-SHA256, AES128-SHA, ECDHE-ECDSA-AES256-GCM-SHA384, ECDHE-RSA-AES256-GCM-SHA384, ECDHE-ECDSA-AES256-SHA, ECDHE-RSA-AES256-SHA, AES256-GCM-SHA384, AES256-SHA"  
# the default endpoint certificates
trustedCertificatesFilePath = "/etc/ssl/certs/ca-certificates.crt"
clientCertPath = "/home/wso2/security/mg.pem"
clientKeyPath = "/home/wso2/security/mg.key"
verifyHostName = true
disableSslVerification = false

[enforcer]
[enforcer.authService]
  port = 8081
  maxMessageSize = 1000000000
  maxHeaderLimit = 8192
  #keep alive time of the external authz connection
  keepAliveTime = 600
  [enforcer.authService.threadPool]
    coreSize = 400
    maxSize = 500
    #keep alive time of threads in seconds
    keepAliveTime = 600
    queueSize = 1000

#Key Store Configuration
[enforcer.keystore]
location = "wso2carbon.jks"
type = "jks"
password = "wso2carbon"

#Trust store configuration
[enforcer.truststore]
location = "/home/wso2/mg/security/client-truststore.jks"
type = "jks"
password = "wso2carbon"

# JWT token authorization configurations. You can provide multiple JWT issuers
# Issuer 1
[[enforcer.jwtTokenConfig]]
    name="Resident Key Manager"
    issuer = "https://localhost:9443/oauth2/token"
    certificateAlias = "wso2carbon"
    # URL of the JWKs endpoint
    jwksURL = ""
    # Validate subscribed APIs
    validateSubscription = false
    # The claim in which the consumer key of the application is coming
    consumerKeyClaim = "azp"

# Configurations for retrieving API and subscription data from API Manager.
[enforcer.eventHub]
    # Enable/ Disable the feature
    enabled = false
    # The API Manager URL
    serviceUrl = "https://localhost:9443/"
    # User name and password of the internal data api.
    [enforcer.eventHub.jmsConnectionParameters]
        # The message broker connection URL.
        eventListeningEndpoints = "amqp://admin:admin@carbon/carbon?brokerlist='tcp://localhost:5672'"

[enforcer.apimCredentials]
    username="admin"
    password="admin"

[controlPlane]
# Control plane's eventHub details
[controlPlane.eventHub]
serviceUrl = "https://localhost:9443/"
username="admin"
password="admin"
environmentLabels = ["Production and Sandbox"]
retryInterval = 5
tlsEnabled=false
publicCertPath="/home/wso2/security/controlplane.pem"
# Message broker connection URL of the control plane
[controlPlane.eventHub.jmsConnectionParameters]
eventListeningEndpoints = "amqp://admin:admin@carbon/carbon?brokerlist='tcp://localhost:5672'"