domain: default
descriptors:
  - key: org
    value: carbon.super
    descriptors:
      - key: vhost
        value: localhost
        descriptors:
          - key: path
            descriptors:
              - key: method
                descriptors:
                  - key: policy
                    value: $_5PerMin
                    rate_limit:
                      unit: minute
                      requests_per_unit: 5
                  - key: policy
                    value: $_3PerMin
                    rate_limit:
                      unit: minute
                      requests_per_unit: 3