version: "3.7"
services:
  router:
    image: wso2/mg-router:4.0.0-m5-SNAPSHOT
    volumes:
      - ./resources/router/security:/home/wso2/security
    ports:
      - "9095:9095"
      - "9000:9000"
    links:
      - adapter
      - enforcer
  adapter:
    image: wso2/mg-adapter:4.0.0-m5-SNAPSHOT
    volumes:  
      - ./resources/adapter/security:/home/wso2/security
      - ./resources/conf:/home/wso2/conf
    ports:
      - "18000:18000" 
      - "9843:9843"
  enforcer:
    image: wso2/mg-enforcer:4.0.0-m5-SNAPSHOT
    volumes:  
      - ./resources/enforcer/security:/home/wso2/mg/security
      - ./resources/conf:/home/wso2/conf
    environment:
      - ADAPTER_HOST=adapter
      - ADAPTER_XDS_PORT=18000
      - ENFORCER_LABEL=enforcer
    ports:
      - "8081:8081"   
