apiVersion: cp.wso2.com/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: application
    app.kubernetes.io/instance: application-sample
    app.kubernetes.io/part-of: test
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: test
  name: application-sample-1
spec:
  uuid: 9ec2b927-47aa-456f-b6de-1959274f3asdasdz
  name: app1
  owner: admin
  policy: 10PerMin
  organization: wso2 # not in the current application.proto
  attributes: 
    attb1: value1
    attb2: value2
  consumerKeys:
    - key: yef14gh8syDvTt56rdtIHYbjF_Ya
      keyManager: Resident Key Manager
  subscriptions:
    - uuid: ff041d1b-be19-4529-a861-86a79905a1aq
      name: sub1
      apiRef: SwaggerPetstore
      policyId: Unlimited
      subscriptionStatus: ACTIVE
      subscriber: Tom # not in the current application_key_mapping.proto
    - uuid: ff041d1b-be19-4529-a861-86a79905a1ad
      name: sub2
      apiRef: PizzaShack
      policyId: Unlimited
      subscriptionStatus: ACTIVE
      subscriber: Bob
