
[project]
org-name= "wso2"
version= "3.1.0"

[platform]
target = "java8"

        [[platform.libraries]]
        module = "jms"
        path = "${MGW-TK_HOME}/lib/dependencies/andes-client-3.3.9.jar"
        artifactId = "andes-client"
        version = "3.3.9"
        groupId = "org.wso2.andes.wso2"

        [[platform.libraries]]
        module = "jms"
        path = "${MGW-TK_HOME}/lib/dependencies/org.wso2.securevault-1.1.1.jar"
        artifactId = "org.wso2.securevault"
        version = "1.1.1"
        groupId = "org.wso2.securevault"

[dependencies]
"wso2/gateway" = { path = "${MGW-TK_HOME}/lib/gateway-balo/gateway-2019r3-java8-3.1.0.balo"}

