# Copyright (c) 2021, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: choreo-connect-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
  - hosts:
      - gw.wso2.com
      - apim.wso2.com
    secretName: tls-secret
  rules:
    - host: apim.wso2.com
      http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: wso2apim
                  port:
                    number: 9443
    - host: gw.wso2.com
      http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: router
                  port:
                    number: 9095

---
# The following ingress resource in only for the debugging purposes
# and check router related config_dumps etc. In a production scenario
# make sure to remove this.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: choreo-connect-ingress-internal
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
  - hosts:
      - internal.wso2.com
  rules:
    - host: internal.wso2.com
      http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: router
                  port:
                    number: 9000
