[project]
org-name= "wso2"
version= "3.2.9"

[platform]
target = "java8"

    [[platform.libraries]]
    path = "../../../target/org.wso2.micro.gateway.core-3.2.10-SNAPSHOT.jar"

    [[platform.libraries]]
    path = "../../../target/lib/dependencies/org.everit.json.schema-1.5.0.wso2.v1.jar"

    [[platform.libraries]]
    path = "../../../target/lib/dependencies/json-3.0.0.wso2v4.jar"

    [[platform.libraries]]
    path = "../../../target/lib/dependencies/log4j-core-2.17.0.jar"

    [[platform.libraries]]
    path = "../../../target/lib/dependencies/log4j-api-2.17.0.jar"

    [[platform.libraries]]
    path = "../../../target/lib/dependencies/nimbus-jose-jwt-8.8.jar"

    [[platform.libraries]]
    path = "../../../target/lib/dependencies/json-smart-2.4.11.jar"

    [[platform.libraries]]
    path = "../../../target/lib/dependencies/asm-1.0.2.jar"

    # jackson libraries are added for the use of default claim retriever implementation
    [[platform.libraries]]
    path = "../../../target/lib/dependencies/jackson-annotations-2.15.2.jar"

    [[platform.libraries]]
    path = "../../../target/lib/dependencies/jackson-core-2.15.2.jar"

    [[platform.libraries]]
    path = "../../../target/lib/dependencies/jackson-databind-2.15.2.jar"

    [[platform.libraries]]
    path = "../../../target/lib/dependencies/org.wso2.carbon.apimgt.common.analytics-9.29.120.jar"

    [[platform.libraries]]
    path = "../../../target/lib/dependencies/org.wso2.am.analytics.publisher.client-1.2.20.jar"

    [[platform.libraries]]
    path = "../../../target/lib/dependencies/ua-parser-1.6.1.wso2v1.jar"

    [[platform.libraries]]
    path = "../../../target/lib/dependencies/azure-core-1.43.0.wso2v1.jar"

    [[platform.libraries]]
    path = "../../../target/lib/dependencies/azure-core-amqp-2.8.9.wso2v1.jar"

    [[platform.libraries]]
    path = "../../../target/lib/dependencies/azure-messaging-eventhubs-5.16.0.wso2v1.jar"

    [[platform.libraries]]
    path = "../../../target/lib/dependencies/reactive-streams-1.0.3.jar"

    [[platform.libraries]]
    path = "../../../target/lib/dependencies/feign-core-13.2.1.jar"

    [[platform.libraries]]
    path = "../../../target/lib/dependencies/feign-slf4j-13.2.1.jar"

    [[platform.libraries]]
    path = "../../../target/lib/dependencies/feign-gson-13.2.1.jar"

    [[platform.libraries]]
    path = "../../../target/lib/dependencies/reactor-core-3.4.31.wso2v1.jar"

    [[platform.libraries]]
    path = "../../../target/lib/dependencies/proton-j-0.33.4.jar"

[dependencies]
"ballerina/java.jms" = "0.8.5"
