[project]
org-name= "wso2"
version= "3.1.0"

[platform]
target = "java8"

    [[platform.libraries]]
    path = "../../../target/org.wso2.micro.gateway.core-3.1.0-SNAPSHOT.jar"

[dependencies]
"wso2/jms" = "0.7.0"