version: "3.7"
# TODO: (VirajSalaka) Fix all the related scripts since this is going to be maintained.
services:
  envoydev:
    build:
      context: ./../../
      dockerfile: docker/with-external-build/envoy/Dockerfile
    volumes:
      - ./../../envoy.yaml:/etc/envoy/envoy.yaml
#    expose:
#      - "80"
#      - "8001"
    ports:
      - "10000:10000"
      - "9000:9000"
    links:
      - pilot
      - filterchain
  pilot:
    build:
      context: ./../../
      dockerfile: docker/with-external-build/control-plane/Dockerfile
    volumes:  
      - ./../../resources/:/home/ubuntu/resources/
      - ./../../target/:/home/ubuntu/pilot/
    ports:
      - "18000:18000" 
  filterchain:
    build:
      context: ./../../
      dockerfile: docker/with-external-build/filter-chain/Dockerfile
    volumes:
      - ./../../filter-core/target:/home/ubuntu
      - ./../../resources/apis:/home/ubuntu/apis
    ports:
      - "8081:8081"
  # zipkin:
  #   image: openzipkin/zipkin
  #   expose:
  #   - "9411"
  #   ports:
  #   - "9411:9411"
