name: Nighly Choreo Connect Integration Tests

on:
  schedule:
    # every day at 8:25pm UTC (1:55am IST )
    - cron:  '25 20 * * *'
  workflow_dispatch:
jobs:
  check_continue:
    runs-on: ubuntu-latest
    name: Check continuing testing
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v2
      - id: should_run
        continue-on-error: true
        name: Check latest commit is less than a day
        run: |
          echo "Branch: " $(git rev-parse --abbrev-ref HEAD)
          count=$(git rev-list --since="24 hours ago" --count HEAD)
          echo "Commits count: $count"
          echo "Commits:"
          git rev-list --since="1 days ago" HEAD

          if [ $count -gt 0 ]; then
            echo "Should continue"
            echo "::set-output name=should_run::true"
          else
            echo "No changes, do not continue"
          echo "::set-output name=should_run::false"
          fi

  build:
    needs: check_continue
    if: ${{ needs.check_continue.outputs.should_run != 'false' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.x'
      - name: Cache M2 Repo
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Cache Go Modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Extract Maven project version
        run: echo ::set-output name=version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        id: extract-project-version
      - name: Print Maven project version
        run: echo ${{ steps.extract-project-version.outputs.version }}
      - name: Build with Maven
        run: |
          export PATH="${HOME}/go/bin:${PATH}"
          export GOFLAGS=-mod=mod
          mvn clean install -PRelease -s .maven/settings.xml \
            -pl '!:integration' -pl '!:mock-backend-server' -pl '!:test-integration'
      - name: Build multi platform Ubuntu images
        run: |
          ./build-ubuntu-multi-platform-images.sh all
      - name: Replace original images with Ubuntu images
        run: |
          TAG=${{ steps.extract-project-version.outputs.version }}
          docker tag wso2/choreo-connect-adapter:$TAG wso2/choreo-connect-adapter:default-alpine
          docker tag wso2/choreo-connect-enforcer:$TAG wso2/choreo-connect-enforcer:default-alpine
          docker tag wso2/choreo-connect-router:$TAG wso2/choreo-connect-router:default-alpine

          # Remove default images to make sure, ubuntu images are properly get replaced
          docker rmi \
            wso2/choreo-connect-adapter:$TAG \
            wso2/choreo-connect-enforcer:$TAG \
            wso2/choreo-connect-router:$TAG

          UBUNTU_TAG=${TAG}-ubuntu-linux-amd64
          docker tag wso2/choreo-connect-adapter:$UBUNTU_TAG wso2/choreo-connect-adapter:$TAG
          docker tag wso2/choreo-connect-enforcer:$UBUNTU_TAG wso2/choreo-connect-enforcer:$TAG
          docker tag wso2/choreo-connect-router:$UBUNTU_TAG wso2/choreo-connect-router:$TAG
      - name: Run integration tests for Ubuntu images
        run: |
          mvn clean install -pl ':integration' -amd -s .maven/settings.xml
      - name: Setup Trivy
        # Using custom Trivy instead of "aquasecurity/trivy-action@0.1.0" to customize the behaviour
        # Run Trivy scan for all images and fail if one failed
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.21.0/trivy_0.21.0_Linux-64bit.tar.gz
          tar -xzf trivy_0.21.0_Linux-64bit.tar.gz
          echo "$(pwd)" >> $GITHUB_PATH
      - name: Trivy Scan
        run: |
          TAG=${{ steps.extract-project-version.outputs.version }}
          SEVERITY="CRITICAL,HIGH,MEDIUM"
          EXIT_CODE=0
          ARGS="--ignore-unfixed" # if the issues is fixed in a later version we can update it

          GREEN='\033[0;32m' # Green colour
          BOLD="\033[1m"
          NC='\033[0m' # No colour

          printf "${GREEN}${BOLD}Default Alpine Images${NC}\n"
          trivy --exit-code 1 --severity "${SEVERITY}" $ARGS wso2/choreo-connect-adapter:default-alpine || EXIT_CODE=$?
          trivy --exit-code 1 --severity "${SEVERITY}" $ARGS wso2/choreo-connect-enforcer:default-alpine || EXIT_CODE=$?
          trivy --exit-code 1 --severity "${SEVERITY}" $ARGS wso2/choreo-connect-router:default-alpine || EXIT_CODE=$?

          printf "${GREEN}${BOLD}Ubuntu AMD Images${NC}\n"
          SUFFIX="-ubuntu-linux-amd64"
          trivy --exit-code 1 --severity "${SEVERITY}" $ARGS wso2/choreo-connect-adapter:${TAG}${SUFFIX} || EXIT_CODE=$?
          trivy --exit-code 1 --severity "${SEVERITY}" $ARGS wso2/choreo-connect-enforcer:$TAG${SUFFIX} || EXIT_CODE=$?
          trivy --exit-code 1 --severity "${SEVERITY}" $ARGS wso2/choreo-connect-router:$TAG${SUFFIX} || EXIT_CODE=$?

          printf "${GREEN}${BOLD}Ubuntu ARM Images${NC}\n"
          SUFFIX="-ubuntu-linux-arm64"
          trivy --exit-code 1 --severity "${SEVERITY}" $ARGS wso2/choreo-connect-adapter:${TAG}${SUFFIX} || EXIT_CODE=$?
          trivy --exit-code 1 --severity "${SEVERITY}" $ARGS wso2/choreo-connect-enforcer:$TAG${SUFFIX} || EXIT_CODE=$?
          trivy --exit-code 1 --severity "${SEVERITY}" $ARGS wso2/choreo-connect-router:$TAG${SUFFIX} || EXIT_CODE=$?

          # error if one of trivy scan failed
          exit $EXIT_CODE
      - name: Choreo Connect Chat Notification
        uses: Co-qn/google-chat-notification@v1
        with:
          name: Choreo Connect Ubuntu Nighly Build
          url: ${{ secrets.NIGHT_BUILD_GCHAT_WEBHOOK }}
          status: ${{ job.status }}
        if: ${{ failure() }}
